
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-music using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219

ROOST_METHOD_HASH=getPhone_705c77f90a
ROOST_METHOD_SIG_HASH=getPhone_39409e28ac

Scenario 1: Retrieve Valid Phone Number

Details:
  TestName: retrieveValidPhoneNumber
  Description: Verify that the getPhone() method correctly returns the phone number when it has been set to a valid value.

Execution:
  Arrange: Create a User_Info object and set its phone field to a valid phone number.
  Act: Call the getPhone() method on the User_Info object.
  Assert: Verify that the returned value matches the phone number that was set.

Validation:
  This test confirms that the getPhone() method correctly retrieves the stored phone number value. It ensures the basic functionality of the getter method works as expected, which is essential for accessing user contact information throughout the application.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Models;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;

class UserInfoGetPhoneTest {

	private User_Info userInfo;

	@BeforeEach
	void setUp() {
		userInfo = new User_Info();
	}

	@Test
	@Tag("valid")
	@DisplayName("Should retrieve valid phone number")
	void retrieveValidPhoneNumber() {
		// Arrange
		String expectedPhone = "+1-555-123-4567";
		userInfo.setPhone(expectedPhone);
		// Act
		String actualPhone = userInfo.getPhone();
		// Assert
		assertEquals(expectedPhone, actualPhone);
	}

	@Test
	@Tag("valid")
	@DisplayName("Should retrieve phone number set through constructor")
	void retrievePhoneNumberSetThroughConstructor() {
		// Arrange
		String expectedPhone = "+44-7700-900123";
		userInfo = new User_Info(1, "photo.jpg", "Rock", "Male", expectedPhone, "instagram.com/user",
				"twitter.com/user", "Reading");
		// Act
		String actualPhone = userInfo.getPhone();
		// Assert
		assertEquals(expectedPhone, actualPhone);
	}

	@Test
	@Tag("valid")
	@DisplayName("Should return null when phone is not set")
	void returnNullWhenPhoneNotSet() {
		// Act
		String actualPhone = userInfo.getPhone();
		// Assert
		assertNull(actualPhone);
	}

	@Test
	@Tag("valid")
	@DisplayName("Should return empty string when phone is set to empty")
	void returnEmptyStringWhenPhoneIsEmpty() {
		// Arrange
		userInfo.setPhone("");
		// Act
		String actualPhone = userInfo.getPhone();
		// Assert
		assertEquals("", actualPhone);
	}

	@Test
	@Tag("valid")
	@DisplayName("Should return updated phone number after changing it")
	void returnUpdatedPhoneAfterChange() {
		// Arrange
		String initialPhone = "123-456-7890";
		String updatedPhone = "987-654-3210";
		userInfo.setPhone(initialPhone);

		// Act - First verification
		assertEquals(initialPhone, userInfo.getPhone());

		// Update phone
		userInfo.setPhone(updatedPhone);

		// Act - Second verification
		String actualPhone = userInfo.getPhone();

		// Assert
		assertEquals(updatedPhone, actualPhone);
	}

}