
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-music-github using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=createAuser_43c81bbbba
ROOST_METHOD_SIG_HASH=createAuser_2684b4910b

Scenario 1: Mismatched passwords should return the mismatch message and avoid persistence

Details:
  TestName: returnsMismatchMessageWhenPasswordsDiffer
  Description: Verifies that AuthController.createAuser returns "Senhas não batem!" when password and confirmpassword differ, and ensures no user credentials are saved and no log entry is written.

Execution:
  Arrange: Create an instance of AuthController. Provide mocked UserAccRepository and LogRepository. Leave other unused dependencies as mocks or null as appropriate.
  Act: Call createAuser with email="user@example.com", password="abc123", confirmpassword="ABC123", username="tester".
  Assert: Assert the returned string equals "Senhas não batem!". Verify that UserAccRepo.save is never called and Log.save is never called.

Validation:
  Confirms that the guard clause using Objects.equals enforces exact equality and prevents side effects (no save or log) when passwords do not match. This preserves data integrity by not creating inconsistent user records.


Scenario 2: Matching passwords should return success and persist both user and log

Details:
  TestName: returnsSuccessAndPersistsWhenPasswordsMatch
  Description: Ensures that when password equals confirmpassword, AuthController.createAuser returns "Sucesso", saves a User_Credentials to UserAccRepo, and saves a corresponding LogModel with the expected values to Log.

Execution:
  Arrange: Create AuthController with mocked UserAccRepository and LogRepository. Replace the Date field (LogModel instance) with a spy or stub that returns a fixed timestamp (e.g., "2026-01-01T00:00:00Z") from getTimeNow (use reflection to set the private field if needed).
  Act: Call createAuser with email="user@example.com", password="abc123", confirmpassword="abc123", username="tester".
  Assert: Assert the returned string equals "Sucesso". Verify UserAccRepo.save is called exactly once with a User_Credentials constructed from the provided email, password, and username. Capture the argument passed to Log.save and verify it is a LogModel created with action="createUser01", entity="User", and the timestamp returned by Date.getTimeNow.

Validation:
  Confirms the happy path behavior: user creation is attempted and a log entry is written with the exact action and entity labels and the controller’s timestamp source. This validates both the result message and critical side effects.


Scenario 3: Both password and confirmpassword null should be treated as equal and succeed

Details:
  TestName: allowsNullPasswordsWhenBothNull
  Description: Validates that Objects.equals treats two null values as equal, allowing the method to proceed with saving and logging, returning "Sucesso".

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Spy/stub the Date.getTimeNow to return a fixed value.
  Act: Call createAuser with email="user@example.com", password=null, confirmpassword=null, username="tester".
  Assert: Assert the returned string equals "Sucesso". Verify UserAccRepo.save and Log.save are each called exactly once.

Validation:
  Ensures the method relies strictly on Objects.equals semantics for equality, and does not block creation when both password fields are null. This documents current behavior for null handling.


Scenario 4: One null password and one non-null should return the mismatch message

Details:
  TestName: returnsMismatchWhenOnePasswordIsNull
  Description: Checks that when one of the password values is null and the other is not, the method returns "Senhas não batem!" and performs no persistence.

Execution:
  Arrange: Mock UserAccRepository and LogRepository.
  Act: Call createAuser with email="user@example.com", password=null, confirmpassword="abc123", username="tester" (and vice versa in a separate assertion if desired).
  Assert: Assert the returned string equals "Senhas não batem!". Verify no calls to UserAccRepo.save or Log.save.

Validation:
  Verifies robust mismatch detection for asymmetric null values, preventing unintended user creation.


Scenario 5: Equal empty-string passwords should succeed

Details:
  TestName: allowsEmptyPasswordsWhenBothEmpty
  Description: Ensures that empty strings are considered equal when both password and confirmpassword are "", resulting in a successful save-and-log and "Sucesso" return.

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Stub Date.getTimeNow.
  Act: Call createAuser with email="user@example.com", password="", confirmpassword="", username="tester".
  Assert: Assert the returned string equals "Sucesso". Verify UserAccRepo.save and Log.save are called exactly once each.

Validation:
  Documents that the controller applies no non-emptiness validation to passwords and proceeds based purely on equality.


Scenario 6: Case-sensitive mismatch in passwords should fail

Details:
  TestName: treatsCaseDifferenceAsMismatch
  Description: Verifies that password comparison is case-sensitive by returning "Senhas não batem!" when values differ by case only.

Execution:
  Arrange: Mock UserAccRepository and LogRepository.
  Act: Call createAuser with password="Password123" and confirmpassword="password123".
  Assert: Assert the returned string equals "Senhas não batem!". Verify no calls to UserAccRepo.save or Log.save.

Validation:
  Clarifies that exact string equality (including case) is required, which is important for security expectations.


Scenario 7: Null email with matching passwords should still return success and persist

Details:
  TestName: savesEvenWhenEmailIsNullIfPasswordsMatch
  Description: Confirms that the controller does not validate the email value; if passwords match, it returns "Sucesso" and performs save and log operations.

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Stub Date.getTimeNow.
  Act: Call createAuser with email=null, password="abc123", confirmpassword="abc123", username="tester".
  Assert: Assert the returned string equals "Sucesso". Verify single calls to UserAccRepo.save and Log.save.

Validation:
  Highlights that input validation for email is not enforced by the controller. This scenario captures the current behavior for upstream/downstream validation considerations.


Scenario 8: Null username with matching passwords should still return success and persist

Details:
  TestName: savesEvenWhenUsernameIsNullIfPasswordsMatch
  Description: Ensures the controller does not validate username; with matching passwords, it proceeds to save and log, returning "Sucesso".

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Stub Date.getTimeNow.
  Act: Call createAuser with email="user@example.com", password="abc123", confirmpassword="abc123", username=null.
  Assert: Assert the returned string equals "Sucesso". Verify calls to UserAccRepo.save and Log.save occur exactly once each.

Validation:
  Documents the absence of username validation and that persistence proceeds solely on password equality.


Scenario 9: Exception during user save should propagate and prevent logging

Details:
  TestName: propagatesExceptionWhenUserSaveFails
  Description: Validates that if UserAccRepo.save throws a runtime exception, the method does not catch it, does not attempt to log, and propagates the exception.

Execution:
  Arrange: Mock UserAccRepository to throw a RuntimeException on save. Mock LogRepository. Stub Date.getTimeNow if needed.
  Act: Invoke createAuser with matching passwords and expect an exception.
  Assert: Assert that a RuntimeException is thrown. Verify Log.save is never called.

Validation:
  Confirms lack of error-handling within the method and ensures logging is not attempted after a failed persistence operation, preserving consistency.


Scenario 10: Exception during log save should propagate after successful user save

Details:
  TestName: propagatesExceptionWhenLogSaveFails
  Description: Ensures that if Log.save throws a runtime exception, the exception is propagated and the method does not return "Sucesso", while confirming the user was saved before the log attempt.

Execution:
  Arrange: Mock UserAccRepository to save without error. Mock LogRepository to throw RuntimeException on save. Stub Date.getTimeNow.
  Act: Call createAuser with matching passwords and expect an exception.
  Assert: Assert that a RuntimeException is thrown. Verify UserAccRepo.save is called once and Log.save is called once.

Validation:
  Verifies operation order and error propagation: user persistence happens before logging, and a logging failure interrupts the response.


Scenario 11: Ensure user is saved before log entry is written

Details:
  TestName: savesUserBeforeWritingLog
  Description: Confirms the sequencing of operations: save to UserAccRepo occurs before Log.save.

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Use an interaction sequence verifier (e.g., in-order verification).
  Act: Call createAuser with matching passwords.
  Assert: Verify that the call to UserAccRepo.save occurs before the call to Log.save.

Validation:
  Ensures the intended order of side effects, which can be important for audit trails and consistency.


Scenario 12: Timestamp is obtained once from the controller’s Date field on success

Details:
  TestName: requestsTimestampFromDateOnceOnSuccess
  Description: Validates that Date.getTimeNow is invoked exactly once when the success path is taken.

Execution:
  Arrange: Replace the Date field with a spy/stubbed LogModel whose getTimeNow returns a fixed value and can be verified for invocation count.
  Act: Call createAuser with matching passwords.
  Assert: Verify getTimeNow is invoked exactly once.

Validation:
  Confirms that the controller fetches the timestamp a single time per operation, aligning with performance and correctness expectations.


Scenario 13: Unused dependencies are not interacted with during create

Details:
  TestName: doesNotUseUnusedDependenciesDuringCreate
  Description: Ensures that JwtUtil and UserInfoRepository are not used by createAuser.

Execution:
  Arrange: Provide mocks for JwtUtil and UserInfoRepository (if injected or set), alongside necessary mocks for UserAccRepository and LogRepository.
  Act: Call createAuser with matching passwords.
  Assert: Verify there are no interactions with JwtUtil and UserInfoRepo.

Validation:
  Documents that createAuser is isolated to user credential persistence and logging, helping prevent unintended coupling.


Scenario 14: Repeated calls with identical inputs consistently succeed and trigger repeated persistence

Details:
  TestName: returnsSuccessOnRepeatedCallsWithSameInputs
  Description: Verifies idempotent response (not idempotent side effects) with repeated identical inputs: each call returns "Sucesso" and triggers its own save and log.

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Stub Date.getTimeNow to return deterministic or sequential values if needed.
  Act: Call createAuser twice with the same email, password, confirmpassword, and username.
  Assert: Assert both calls return "Sucesso". Verify UserAccRepo.save is called twice and Log.save is called twice.

Validation:
  Shows that the controller does not enforce uniqueness or deduplication and that each call results in persistence and logging.


Scenario 15: Accepts very long input strings when passwords match

Details:
  TestName: acceptsVeryLongInputsWhenPasswordsMatch
  Description: Ensures the method handles large input sizes without additional validation, returning "Sucesso" and performing persistence and logging.

Execution:
  Arrange: Construct very long strings for email, password, and username; ensure password equals confirmpassword. Mock UserAccRepository and LogRepository.
  Act: Call createAuser with the long inputs.
  Assert: Assert the returned string equals "Sucesso". Verify UserAccRepo.save and Log.save are called exactly once each.

Validation:
  Demonstrates that the controller imposes no length constraints and relies on downstream components for such validation.


Scenario 16: Leading/trailing whitespace in equal passwords still succeeds

Details:
  TestName: treatsWhitespaceAsSignificantInPasswordMatching
  Description: Confirms that the controller does not trim passwords; equal strings with whitespace pass and result in success.

Execution:
  Arrange: Mock UserAccRepository and LogRepository.
  Act: Call createAuser with password="  pass  " and confirmpassword="  pass  ".
  Assert: Assert the returned string equals "Sucesso". Verify UserAccRepo.save and Log.save each invoked once.

Validation:
  Captures current behavior that whitespace is treated as part of the password, important for avoiding silent data transformations.


Scenario 17: Special characters in credentials are accepted when passwords match

Details:
  TestName: acceptsSpecialCharactersWhenPasswordsMatch
  Description: Ensures the method handles special characters (e.g., symbols, Unicode) in email, password, and username, provided passwords match.

Execution:
  Arrange: Mock UserAccRepository and LogRepository. Stub Date.getTimeNow.
  Act: Call createAuser with email="üser+alias@example-domain.com", password="p@$$w0rd!✓", confirmpassword="p@$$w0rd!✓", username="téßt_user-✓".
  Assert: Assert the returned string equals "Sucesso". Verify one call to UserAccRepo.save and one call to Log.save.

Validation:
  Demonstrates that the controller does not constrain character sets and properly delegates to persistence and logging when passwords match.


Scenario 18: Log content uses exact action and entity constants

Details:
  TestName: writesLogWithExpectedActionAndEntity
  Description: Focuses on verifying that the created log entry uses the exact strings "createUser01" for action and "User" for entity, alongside the timestamp from Date.getTimeNow.

Execution:
  Arrange: Mock LogRepository with an argument captor for LogModel. Replace Date with a spy/stub returning a known timestamp. Mock UserAccRepository to accept saves.
  Act: Call createAuser with matching passwords.
  Assert: Capture the LogModel passed to Log.save and verify it was created with action="createUser01", entity="User", and the stubbed timestamp.

Validation:
  Ensures audit log semantics are precise and unchanged, which is critical for traceability and monitoring.

*/

// ********RoostGPT********

package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.*;
import com.medeiros.SPRINGProject.Security.JwtUtil;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.bind.annotation.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.Objects;

@ExtendWith(MockitoExtension.class)
public class AuthControllerCreateAuserTest {

	private AuthController controller;

	@Mock
	private UserAccRepository userAccRepository;

	@Mock
	private UserInfoRepository userInfoRepository;

	@Mock
	private LogRepository logRepository;

	@Mock
	private JwtUtil jwtUtil;

	private static final String FIXED_TIMESTAMP = "2026-01-01T00:00:00Z"; // TODO adjust
																			// if project
																			// expectations
																			// change

	@BeforeEach
	public void setUp() throws Exception {
		controller = new AuthController();
		setPrivateField(controller, "UserAccRepo", userAccRepository);
		setPrivateField(controller, "Log", logRepository);
		setPrivateField(controller, "JwtToken", jwtUtil);
		setPrivateField(controller, "UserInfoRepo", userInfoRepository);
		// Default Date field as a real LogModel; individual tests can override with a spy
		setPrivateField(controller, "Date", new LogModel());
	}

	@Test
	@Tag("invalid")
	public void returnsMismatchMessageWhenPasswordsDiffer() {
		String result = controller.createAuser("user@example.com", "abc123", "ABC123", "tester");
		assertEquals((String) "Senhas não batem!", (String) result);
		verify(userAccRepository, never()).save(any(User_Credentials.class));
		verify(logRepository, never()).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void returnsSuccessAndPersistsWhenPasswordsMatch() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String email = "user@example.com";
		String password = "abc123";
		String username = "tester";
		String result = controller.createAuser(email, password, password, username);
		assertEquals((String) "Sucesso", (String) result);
		ArgumentCaptor<User_Credentials> userCaptor = ArgumentCaptor.forClass(User_Credentials.class);
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(userAccRepository, times(1)).save(userCaptor.capture());
		verify(logRepository, times(1)).save(logCaptor.capture());
		// Verify user content via reflection-based search of String fields
		assertTrue(objectContainsStringValue(userCaptor.getValue(), (String) email));
		assertTrue(objectContainsStringValue(userCaptor.getValue(), (String) password));
		assertTrue(objectContainsStringValue(userCaptor.getValue(), (String) username));
		// Verify log content: action, entity, timestamp
		LogModel capturedLog = logCaptor.getValue();
		assertNotNull(capturedLog);
		assertTrue(objectContainsStringValue(capturedLog, (String) "createUser01"));
		assertTrue(objectContainsStringValue(capturedLog, (String) "User"));
		assertTrue(objectContainsStringValue(capturedLog, (String) FIXED_TIMESTAMP));
	}

	@Test
	@Tag("valid")
	public void allowsNullPasswordsWhenBothNull() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String result = controller.createAuser("user@example.com", null, null, "tester");
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("invalid")
	public void returnsMismatchWhenOnePasswordIsNull() {
		String result1 = controller.createAuser("user@example.com", null, "abc123", "tester");
		assertEquals((String) "Senhas não batem!", (String) result1);
		verify(userAccRepository, never()).save(any(User_Credentials.class));
		verify(logRepository, never()).save(any(LogModel.class));
		String result2 = controller.createAuser("user@example.com", "abc123", null, "tester");
		assertEquals((String) "Senhas não batem!", (String) result2);
		verify(userAccRepository, never()).save(any(User_Credentials.class));
		verify(logRepository, never()).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void allowsEmptyPasswordsWhenBothEmpty() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String result = controller.createAuser("user@example.com", "", "", "tester");
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("invalid")
	public void treatsCaseDifferenceAsMismatch() {
		String result = controller.createAuser("user@example.com", "Password123", "password123", "tester");
		assertEquals((String) "Senhas não batem!", (String) result);
		verify(userAccRepository, never()).save(any(User_Credentials.class));
		verify(logRepository, never()).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void savesEvenWhenEmailIsNullIfPasswordsMatch() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String result = controller.createAuser(null, "abc123", "abc123", "tester");
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void savesEvenWhenUsernameIsNullIfPasswordsMatch() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String result = controller.createAuser("user@example.com", "abc123", "abc123", null);
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("integration")
	public void propagatesExceptionWhenUserSaveFails() throws Exception {
		doThrow(new RuntimeException("DB save error")).when(userAccRepository).save(any(User_Credentials.class));
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		assertThrows(RuntimeException.class,
				() -> controller.createAuser("user@example.com", "abc123", "abc123", "tester"));
		verify(logRepository, never()).save(any(LogModel.class));
	}

	@Test
	@Tag("integration")
	public void propagatesExceptionWhenLogSaveFails() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		doThrow(new RuntimeException("Log save error")).when(logRepository).save(any(LogModel.class));
		assertThrows(RuntimeException.class,
				() -> controller.createAuser("user@example.com", "abc123", "abc123", "tester"));
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("integration")
	public void savesUserBeforeWritingLog() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		InOrder inOrder = inOrder(userAccRepository, logRepository);
		inOrder.verify(userAccRepository).save(any(User_Credentials.class));
		inOrder.verify(logRepository).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void requestsTimestampFromDateOnceOnSuccess() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		verify(dateSpy, times(1)).getTimeNow();
	}

	@Test
	@Tag("valid")
	public void doesNotUseUnusedDependenciesDuringCreate() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		verifyNoInteractions(jwtUtil);
		verifyNoInteractions(userInfoRepository);
	}

	@Test
	@Tag("valid")
	public void returnsSuccessOnRepeatedCallsWithSameInputs() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn("2026-01-01T00:00:00Z", "2026-01-01T00:00:01Z").when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String res1 = controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		String res2 = controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		assertEquals((String) "Sucesso", (String) res1);
		assertEquals((String) "Sucesso", (String) res2);
		verify(userAccRepository, times(2)).save(any(User_Credentials.class));
		verify(logRepository, times(2)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void acceptsVeryLongInputsWhenPasswordsMatch() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String longEmail = generateLongString("user", 1000) + "@example.com";
		String longPassword = generateLongString("p", 2000);
		String longUsername = generateLongString("u", 1500);
		String result = controller.createAuser(longEmail, longPassword, longPassword, longUsername);
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void treatsWhitespaceAsSignificantInPasswordMatching() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String result = controller.createAuser("user@example.com", "  pass  ", "  pass  ", "tester");
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void acceptsSpecialCharactersWhenPasswordsMatch() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		String email = "üser+alias@example-domain.com";
		String password = "p@$w0rd!✓";
		String username = "téßt_user-✓";
		String result = controller.createAuser(email, password, password, username);
		assertEquals((String) "Sucesso", (String) result);
		verify(userAccRepository, times(1)).save(any(User_Credentials.class));
		verify(logRepository, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void writesLogWithExpectedActionAndEntity() throws Exception {
		LogModel dateSpy = Mockito.spy(new LogModel());
		doReturn(FIXED_TIMESTAMP).when(dateSpy).getTimeNow();
		setPrivateField(controller, "Date", dateSpy);
		controller.createAuser("user@example.com", "abc123", "abc123", "tester");
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(logRepository, times(1)).save(logCaptor.capture());
		LogModel capturedLog = logCaptor.getValue();
		assertNotNull(capturedLog);
		assertTrue(objectContainsStringValue(capturedLog, (String) "createUser01"));
		assertTrue(objectContainsStringValue(capturedLog, (String) "User"));
		assertTrue(objectContainsStringValue(capturedLog, (String) FIXED_TIMESTAMP));
	}

	// Helper methods
	private static void setPrivateField(Object target, String fieldName, Object value) throws Exception {
		Field field = getFieldRecursive(target.getClass(), fieldName);
		field.setAccessible(true);
		field.set(target, value);
	}

	private static Field getFieldRecursive(Class<?> cls, String fieldName) throws NoSuchFieldException {
		Class<?> current = cls;
		while (current != null) {
			try {
				return current.getDeclaredField(fieldName);
			}
			catch (NoSuchFieldException ignored) {
				current = current.getSuperclass();
			}
		}
		throw new NoSuchFieldException(fieldName);
	}

	private static boolean objectContainsStringValue(Object obj, String expected) {
		if (obj == null || expected == null)
			return false;
		List<String> values = getAllStringFieldValues(obj);
		for (String v : values) {
			if (expected.equals(v)) {
				return true;
			}
		}
		return false;
	}

	private static List<String> getAllStringFieldValues(Object obj) {
		List<String> values = new ArrayList<>();
		Class<?> current = obj.getClass();
		while (current != null) {
			Field[] fields = current.getDeclaredFields();
			for (Field f : fields) {
				if (f.getType() == String.class) {
					try {
						f.setAccessible(true);
						Object val = f.get(obj);
						if (val instanceof String) {
							values.add((String) val);
						}
					}
					catch (IllegalAccessException ignored) {
					}
				}
			}
			current = current.getSuperclass();
		}
		return values;
	}

	private static String generateLongString(String seed, int repeat) {
		StringBuilder sb = new StringBuilder(seed.length() * repeat);
		for (int i = 0; i < repeat; i++) {
			sb.append(seed);
		}
		return sb.toString();
	}

}