
// ********RoostGPT********
/*
Test generated by RoostGPT for test maven-music-github using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=createProduct_2b4ce50b8c
ROOST_METHOD_SIG_HASH=createProduct_7aa14a7887

Scenario 1: Successful creation returns the expected success message and performs saves

Details:
  TestName: createProductReturnsSuccessMessageOnValidInput
  Description: Verifies that when valid parameters are provided, MarketController.createProduct constructs a ProductModel, saves it through ProductModelRepository, logs the operation through LogRepository, and returns the exact success message.

Execution:
  Arrange: Create a MarketController instance. Inject mock ProductModelRepository into controller.ProductRepository and mock LogRepository into controller.Log. Stub controller.Date.getTimeNow() to return a fixed timestamp value. Prepare typical input values: description="Guitar", price=199.99, musicId=10, userId=5, listProduct="Strings,Capo".
  Act: Invoke createProduct("Guitar", 199.99, 10, 5, "Strings,Capo").
  Assert: Assert that the returned String equals "Produto Criado". Verify ProductRepository.save was called exactly once with a ProductModel constructed from the same inputs. Verify Log.save was called exactly once with a LogModel representing route "product/create/{userid}", entity "Product", and the stubbed timestamp.

Validation:
  Confirms end-to-end controller behavior for the happy path: correct message, one product save, one log save, and correct use of the fixed log route string. Ensures basic business flow is intact.

Scenario 2: ProductRepository.save is invoked once with a ProductModel reflecting all inputs

Details:
  TestName: createProductSavesProductWithAllProvidedFields
  Description: Ensures that the ProductModel passed to ProductRepository.save contains description, price, musicId, userId, and listProduct exactly as provided to the controller method.

Execution:
  Arrange: Instantiate MarketController with mocks for ProductRepository and Log. Optionally stub Date.getTimeNow() to any value. Choose inputs: description="Piano", price=5000.0, musicId=22, userId=101, listProduct="Bench,Sheet Music".
  Act: Call createProduct("Piano", 5000.0, 22, 101, "Bench,Sheet Music").
  Assert: Capture the ProductModel argument passed to ProductRepository.save and assert its internal state matches the inputs (via reflection or argument matchers that compare constructor-initialized fields). Also verify save was called exactly once.

Validation:
  Verifies that data flows unmodified from method parameters into the ProductModel that is persisted, ensuring no reordering, transformation, or omission of fields.

Scenario 3: LogRepository.save is invoked once with the expected route, entity, and timestamp

Details:
  TestName: createProductLogsWithExpectedRouteEntityAndTimestamp
  Description: Validates that the controller constructs LogModel with route "product/create/{userid}" (literal), entity "Product", and timestamp from Date.getTimeNow().

Execution:
  Arrange: Create MarketController. Inject mocks for ProductRepository and Log. Stub Date.getTimeNow() to a known time value (e.g., "2026-05-03T10:00:00Z" or a fixed long). Use any valid product inputs.
  Act: Invoke createProduct with valid inputs.
  Assert: Capture the LogModel passed to Log.save and assert: route=="product/create/{userid}", entityName=="Product", timestamp==stubbed time. Verify Log.save was called exactly once.

Validation:
  Ensures logging is consistent and relies on the controller’s Date field, using the constant route string and expected entity tag.

Scenario 4: Operations occur in correct order: product is saved before log is saved

Details:
  TestName: createProductSavesProductBeforeWritingLog
  Description: Ensures that ProductRepository.save is called prior to Log.save, maintaining intended operation order.

Execution:
  Arrange: Instantiate MarketController with mocks for ProductRepository and Log; stub Date.getTimeNow(). Prepare any valid inputs.
  Act: Call createProduct with valid inputs.
  Assert: Verify the call order: ProductRepository.save is invoked before Log.save (using ordered verification).

Validation:
  Correct sequencing helps guarantee that a product is persisted before the action is logged, aligning with expected transactional semantics.

Scenario 5: Zero price is accepted and still results in save and log

Details:
  TestName: createProductAcceptsZeroPrice
  Description: Verifies behavior when price is 0.0—no validation occurs, and the product is still saved and logged.

Execution:
  Arrange: Set up controller and mocks, stub Date.getTimeNow(). Inputs: description="Harmonica", price=0.0, musicId=3, userId=7, listProduct="Case".
  Act: Invoke createProduct("Harmonica", 0.0, 3, 7, "Case").
  Assert: Assert returned value is "Produto Criado". Verify ProductRepository.save and Log.save each invoked once with appropriate objects.

Validation:
  Confirms lack of price validation, documenting that zero price is permitted by the controller layer.

Scenario 6: Negative price is accepted and still results in save and log

Details:
  TestName: createProductAcceptsNegativePrice
  Description: Ensures the controller does not reject negative prices, continuing to save and log.

Execution:
  Arrange: Prepare controller and mocks, stub Date.getTimeNow(). Inputs: description="Flute", price=-10.5, musicId=12, userId=9, listProduct="Cleaning Kit".
  Act: Call createProduct("Flute", -10.5, 12, 9, "Cleaning Kit").
  Assert: Assert returned value equals "Produto Criado". Verify ProductRepository.save and Log.save called once each.

Validation:
  Captures current behavior (no validation in controller) for negative price, important for defining future validation needs.

Scenario 7: Extremely large price (Double.MAX_VALUE) is passed through

Details:
  TestName: createProductHandlesVeryLargePrice
  Description: Tests that a very large price is forwarded to the ProductModel and saved, and the flow completes with logging and success message.

Execution:
  Arrange: Controller with mocked repositories; stub Date.getTimeNow(). Inputs: description="Grand Piano", price=Double.MAX_VALUE, musicId=77, userId=1, listProduct="Bench,Cover".
  Act: Invoke createProduct with those arguments.
  Assert: Assert return equals "Produto Criado". Verify ProductRepository.save received a ProductModel with the given price and Log.save called once.

Validation:
  Ensures numeric extremes are handled without controller-level overflow checks, highlighting potential persistence constraints externally.

Scenario 8: NaN price is forwarded (controller-level) and still attempts save and log

Details:
  TestName: createProductForwardsNaNPriceToRepository
  Description: Confirms the controller does not guard against Double.NaN and still attempts to persist and log.

Execution:
  Arrange: Controller with mocked repositories; stub Date.getTimeNow(). Inputs: description="Synth", price=Double.NaN, musicId=5, userId=2, listProduct="Stand".
  Act: Call createProduct with these inputs.
  Assert: Assert return is "Produto Criado". Verify ProductRepository.save and Log.save each called once (stubbing repository to accept NaN).

Validation:
  Documents that the controller layer is agnostic to special double values, which may inform validation or persistence strategy elsewhere.

Scenario 9: Negative musicId is accepted and still saved

Details:
  TestName: createProductAcceptsNegativeMusicId
  Description: Ensures musicId can be negative at controller level without blocking save/log.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: description="Drums", price=300.0, musicId=-42, userId=88, listProduct="Sticks,Seat".
  Act: Invoke createProduct.
  Assert: Return equals "Produto Criado"; verify one save on ProductRepository and one log on Log.

Validation:
  Captures absence of ID validation, which may be relevant for domain constraints later.

Scenario 10: Zero userId is accepted and forwarded

Details:
  TestName: createProductAcceptsZeroUserId
  Description: Ensures that userId=0 does not prevent saving or logging.

Execution:
  Arrange: Mocks and controller ready; stub Date.getTimeNow(). Inputs: description="Bass", price=450.0, musicId=15, userId=0, listProduct="Strap".
  Act: Call createProduct.
  Assert: Confirm "Produto Criado" is returned and both repositories receive a single call to save.

Validation:
  Documents current permissiveness regarding the path variable userId, useful for security or validation considerations.

Scenario 11: Empty description string is preserved and does not block save

Details:
  TestName: createProductAllowsEmptyDescription
  Description: Checks that an empty description "" is passed through into the ProductModel and save/log still occur.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: description="", price=99.0, musicId=9, userId=12, listProduct="Bag".
  Act: Invoke createProduct.
  Assert: Assert return equals "Produto Criado". Capture ProductModel to assert the description remains empty. Verify both save calls occur once.

Validation:
  Ensures inputs are not trimmed or validated by the controller, preserving the exact user-provided string.

Scenario 12: Empty listProduct string is preserved and does not block save

Details:
  TestName: createProductAllowsEmptyListProduct
  Description: Ensures listProduct="" is accepted and persisted without changes.

Execution:
  Arrange: Set controller and mocks; stub Date.getTimeNow(). Inputs: description="Violin", price=999.0, musicId=31, userId=4, listProduct="".
  Act: Invoke createProduct.
  Assert: Assert return equals "Produto Criado". Capture ProductModel and assert listProduct is empty. Verify both save calls occur once.

Validation:
  Demonstrates that optional-like string inputs are allowed empty at controller layer.

Scenario 13: Special characters and Unicode are preserved

Details:
  TestName: createProductPreservesUnicodeAndSpecialCharacters
  Description: Verifies that description and listProduct with Unicode, emojis, and special characters are passed through intact.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: description="Cello 🎻 – Série Édition", price=1200.5, musicId=55, userId=13, listProduct="Arco,Resina,Estojo™".
  Act: Call createProduct.
  Assert: Assert return equals "Produto Criado". Capture ProductModel and assert fields contain the exact Unicode/special characters. Verify save and log each once.

Validation:
  Ensures controller does not alter encoding or sanitize strings, which is important for internationalization.

Scenario 14: Whitespace-only description is kept as-is

Details:
  TestName: createProductRetainsWhitespaceOnlyDescription
  Description: Ensures a description of only spaces is not trimmed by the controller.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: description="   ", price=10.0, musicId=2, userId=3, listProduct="Pick".
  Act: Invoke createProduct.
  Assert: Assert return equals "Produto Criado". Capture ProductModel and assert description remains "   ". Verify saves occur once each.

Validation:
  Demonstrates that the controller does not mutate whitespace, which may be significant for later validation rules.

Scenario 15: If ProductRepository.save throws, the exception propagates and Log.save is not called

Details:
  TestName: createProductPropagatesExceptionWhenProductSaveFails
  Description: Validates error handling when the product persistence step fails with a runtime exception.

Execution:
  Arrange: Controller with mocks; configure ProductRepository.save to throw a RuntimeException. Stub Date.getTimeNow(). Inputs: any valid parameters.
  Act: Invoke createProduct and expect a RuntimeException to be thrown.
  Assert: Assert that an exception is thrown and no return value is produced. Verify that Log.save was never called.

Validation:
  Confirms lack of try/catch in controller and that logging does not occur when product persistence fails, preventing misleading log entries.

Scenario 16: If Log.save throws, the exception propagates after product save

Details:
  TestName: createProductPropagatesExceptionWhenLogSaveFails
  Description: Ensures that a logging failure after a successful product save results in an exception being thrown by the controller.

Execution:
  Arrange: Controller with mocks; ProductRepository.save succeeds; configure Log.save to throw a RuntimeException. Inputs: any valid parameters.
  Act: Invoke createProduct and expect a RuntimeException to be thrown.
  Assert: Assert that an exception is thrown. Verify ProductRepository.save was called once. Verify Log.save was called once and then failed.

Validation:
  Confirms side-effect sequence: product may be persisted even if logging fails, and the controller does not mask logging errors.

Scenario 17: The timestamp used in the log equals the value from Date.getTimeNow

Details:
  TestName: createProductUsesDateFieldForLogTimestamp
  Description: Confirms that the controller uses its Date field (LogModel instance) to obtain the logging timestamp.

Execution:
  Arrange: Controller with mocks; replace controller.Date with a stubbed LogModel where getTimeNow() returns a known fixed value. Inputs: any valid parameters.
  Act: Invoke createProduct.
  Assert: Capture LogModel passed to Log.save and assert that its timestamp equals the stubbed fixed value.

Validation:
  Verifies the dependency usage on the Date field rather than any external or system time source.

Scenario 18: Returned message is exactly "Produto Criado" with correct casing and spacing

Details:
  TestName: createProductReturnsExactPortugueseMessage
  Description: Ensures the return value is the exact literal "Produto Criado".

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: any valid parameters.
  Act: Invoke createProduct.
  Assert: Assert that the returned String equals exactly "Produto Criado" (case-sensitive, includes space).

Validation:
  Protects against inadvertent changes in user-facing response messages.

Scenario 19: No unexpected repository interactions occur during creation

Details:
  TestName: createProductDoesNotPerformUnrelatedRepositoryOperations
  Description: Ensures that only ProductRepository.save and Log.save are invoked, and methods like findAll or deleteById are not called.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: any valid parameters.
  Act: Call createProduct.
  Assert: Verify only one call to ProductRepository.save and one call to Log.save; verify no interactions with ProductRepository.findAll, ProductRepository.deleteById, or other methods.

Validation:
  Confirms that createProduct remains focused on creation and logging without side effects.

Scenario 20: Log route string remains literal "product/create/{userid}" and does not interpolate userId

Details:
  TestName: createProductUsesLiteralRouteInLog
  Description: Validates that the log path is the literal "product/create/{userid}" and does not substitute the actual userId.

Execution:
  Arrange: Controller with mocks; stub Date.getTimeNow(). Inputs: choose a distinctive userId (e.g., 9999).
  Act: Invoke createProduct with that userId.
  Assert: Capture the LogModel passed to Log.save and assert the route equals exactly "product/create/{userid}" (no interpolation).

Validation:
  Documents current logging design, which uses a literal placeholder rather than the concrete path value, important for log analysis expectations.

*/

// ********RoostGPT********
package com.medeiros.SPRINGProject.Controllers;

import com.medeiros.SPRINGProject.Models.LogModel;
import com.medeiros.SPRINGProject.Models.LogRepository;
import com.medeiros.SPRINGProject.Models.ProductModel;
import com.medeiros.SPRINGProject.Models.ProductModelRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InOrder;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@ExtendWith(MockitoExtension.class)
public class MarketControllerCreateProductTest {

	@Mock
	private ProductModelRepository ProductRepository;

	@Mock
	private LogRepository Log;

	@InjectMocks
	private MarketController controller;

	private static final String FIXED_TIME = (String) "2026-05-03T10:00:00Z"; // NOTE:
																				// Exact
																				// timestamp
																				// assertion
																				// removed
																				// as
																				// createProduct
																				// uses
																				// internal
																				// Date.getTimeNow()

	@BeforeEach
	public void setup() {
		// Removed stubbing of Date.getTimeNow() since the controller uses its own Date
		// field (private LogModel Date = new LogModel()).
		// To assert an exact timestamp, business logic would need to allow injecting a
		// clock or time provider.
	}

	@Test
	@Tag("valid")
	public void testCreateProductReturnsSuccessMessageOnValidInput() {
		String description = (String) "Guitar";
		double price = (double) 199.99d;
		int musicId = (int) 10;
		int userId = (int) 5;
		String listProduct = (String) "Strings,Capo";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		assertTrue(objectHasStringFieldWithValue(productCaptor.getValue(), (String) description));
		assertTrue(objectHasDoubleFieldWithValue(productCaptor.getValue(), (double) price));
		assertTrue(objectHasIntFieldWithValue(productCaptor.getValue(), (int) musicId));
		assertTrue(objectHasIntFieldWithValue(productCaptor.getValue(), (int) userId));
		assertTrue(objectHasStringFieldWithValue(productCaptor.getValue(), (String) listProduct));
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(Log, times(1)).save(logCaptor.capture());
		LogModel logData = logCaptor.getValue();
		assertNotNull((Object) logData);
		assertTrue(objectHasStringFieldWithValue(logData, (String) "product/create/{userid}"));
		assertTrue(objectHasStringFieldWithValue(logData, (String) "Product"));
		// NOTE: Exact timestamp assertion removed due to non-injectable Date field;
		// consider enhancing business logic to inject time source
	}

	@Test
	@Tag("valid")
	public void testCreateProductSavesProductWithAllProvidedFields() {
		String description = (String) "Piano";
		double price = (double) 5000.0d;
		int musicId = (int) 22;
		int userId = (int) 101;
		String listProduct = (String) "Bench,Sheet Music";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		ProductModel saved = productCaptor.getValue();
		assertNotNull((Object) saved);
		assertTrue(objectHasStringFieldWithValue(saved, (String) description));
		assertTrue(objectHasDoubleFieldWithValue(saved, (double) price));
		assertTrue(objectHasIntFieldWithValue(saved, (int) musicId));
		assertTrue(objectHasIntFieldWithValue(saved, (int) userId));
		assertTrue(objectHasStringFieldWithValue(saved, (String) listProduct));
	}

	@Test
	@Tag("valid")
	public void testCreateProductLogsWithExpectedRouteEntityAndTimestamp() {
		String result = (String) controller.createProduct((String) "Any", (double) 1.0d, (int) 1, (int) 1,
				(String) "Any");
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(Log, times(1)).save(logCaptor.capture());
		LogModel logged = logCaptor.getValue();
		assertNotNull((Object) logged);
		assertTrue(objectHasStringFieldWithValue(logged, (String) "product/create/{userid}"));
		assertTrue(objectHasStringFieldWithValue(logged, (String) "Product"));
		// NOTE: Exact timestamp assertion removed; see comment in setup()
	}

	@Test
	@Tag("valid")
	public void testCreateProductSavesProductBeforeWritingLog() {
		String description = (String) "OrderCheck";
		double price = (double) 10.0d;
		int musicId = (int) 2;
		int userId = (int) 3;
		String listProduct = (String) "Pick";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		InOrder inOrder = inOrder(ProductRepository, Log);
		inOrder.verify(ProductRepository, times(1)).save(any(ProductModel.class));
		inOrder.verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductAcceptsZeroPrice() {
		String description = (String) "Harmonica";
		double price = (double) 0.0d;
		int musicId = (int) 3;
		int userId = (int) 7;
		String listProduct = (String) "Case";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("invalid")
	public void testCreateProductAcceptsNegativePrice() {
		String description = (String) "Flute";
		double price = (double) -10.5d;
		int musicId = (int) 12;
		int userId = (int) 9;
		String listProduct = (String) "Cleaning Kit";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductHandlesVeryLargePrice() {
		String description = (String) "Grand Piano";
		double price = (double) Double.MAX_VALUE;
		int musicId = (int) 77;
		int userId = (int) 1;
		String listProduct = (String) "Bench,Cover";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		assertTrue(objectHasDoubleFieldWithValue(productCaptor.getValue(), (double) price));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductForwardsNaNPriceToRepository() {
		String description = (String) "Synth";
		double price = (double) Double.NaN;
		int musicId = (int) 5;
		int userId = (int) 2;
		String listProduct = (String) "Stand";
		String result = (String) controller.createProduct(description, price, musicId, userId, listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		assertTrue(objectHasNaNDoubleField(productCaptor.getValue()));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("invalid")
	public void testCreateProductAcceptsNegativeMusicId() {
		String result = (String) controller.createProduct((String) "Drums", (double) 300.0d, (int) -42, (int) 88,
				(String) "Sticks,Seat");
		assertEquals((String) "Produto Criado", (String) result);
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductAcceptsZeroUserId() {
		String result = (String) controller.createProduct((String) "Bass", (double) 450.0d, (int) 15, (int) 0,
				(String) "Strap");
		assertEquals((String) "Produto Criado", (String) result);
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductAllowsEmptyDescription() {
		String description = (String) "";
		String result = (String) controller.createProduct(description, (double) 99.0d, (int) 9, (int) 12,
				(String) "Bag");
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		assertTrue(objectHasStringFieldWithValue(productCaptor.getValue(), (String) description));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductAllowsEmptyListProduct() {
		String listProduct = (String) "";
		String result = (String) controller.createProduct((String) "Violin", (double) 999.0d, (int) 31, (int) 4,
				listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		assertTrue(objectHasStringFieldWithValue(productCaptor.getValue(), (String) listProduct));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void testCreateProductPreservesUnicodeAndSpecialCharacters() {
		String description = (String) "Cello 🎻 – Série Édition";
		String listProduct = (String) "Arco,Resina,Estojo™";
		String result = (String) controller.createProduct(description, (double) 1200.5d, (int) 55, (int) 13,
				(String) listProduct);
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository, times(1)).save(productCaptor.capture());
		ProductModel saved = productCaptor.getValue();
		assertTrue(objectHasStringFieldWithValue(saved, (String) description));
		assertTrue(objectHasStringFieldWithValue(saved, (String) listProduct));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("boundary")
	public void testCreateProductRetainsWhitespaceOnlyDescription() {
		String description = (String) "   ";
		String result = (String) controller.createProduct(description, (double) 10.0d, (int) 2, (int) 3,
				(String) "Pick");
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<ProductModel> productCaptor = ArgumentCaptor.forClass(ProductModel.class);
		verify(ProductRepository).save(productCaptor.capture());
		assertTrue(objectHasStringFieldWithValue(productCaptor.getValue(), (String) description));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
    @Tag("invalid")
    public void testCreateProductPropagatesExceptionWhenProductSaveFails() {
        when(ProductRepository.save(any(ProductModel.class))).thenThrow(new RuntimeException("save failed"));
        assertThrows(RuntimeException.class, () -> controller.createProduct((String) "X", (double) 1.0d, (int) 1, (int) 1, (String) "Y"));
        verify(Log, never()).save(any(LogModel.class));
    }

	@Test
	@Tag("invalid")
	public void testCreateProductPropagatesExceptionWhenLogSaveFails() {
		doThrow(new RuntimeException("log fails")).when(Log).save(any(LogModel.class));
		assertThrows(RuntimeException.class,
				() -> controller.createProduct((String) "Y", (double) 2.0d, (int) 2, (int) 2, (String) "Z"));
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
	}

	@Test
	@Tag("valid")
	public void testCreateProductUsesDateFieldForLogTimestamp() {
		String result = (String) controller.createProduct((String) "Item", (double) 12.34d, (int) 3, (int) 4,
				(String) "List");
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(Log, times(1)).save(logCaptor.capture());
		LogModel captured = logCaptor.getValue();
		assertNotNull((Object) captured);
		// NOTE: Exact timestamp value assertion removed due to internal
		// Date.getTimeNow(); consider making time source injectable for deterministic
		// tests
	}

	@Test
	@Tag("valid")
	public void testCreateProductReturnsExactPortugueseMessage() {
		String result = (String) controller.createProduct((String) "Any", (double) 1.0d, (int) 1, (int) 1,
				(String) "Any");
		assertEquals((String) "Produto Criado", (String) result);
	}

	@Test
	@Tag("valid")
	public void testCreateProductDoesNotPerformUnrelatedRepositoryOperations() {
		String result = (String) controller.createProduct((String) "Any", (double) 1.0d, (int) 1, (int) 1,
				(String) "Any");
		assertEquals((String) "Produto Criado", (String) result);
		verify(ProductRepository, times(1)).save(any(ProductModel.class));
		verify(Log, times(1)).save(any(LogModel.class));
		verify(ProductRepository, never()).findAll();
		verify(ProductRepository, never()).deleteById(anyInt());
		verifyNoMoreInteractions(ProductRepository, Log);
	}

	@Test
	@Tag("valid")
	public void testCreateProductUsesLiteralRouteInLog() {
		int distinctiveUserId = (int) 9999; // TODO: adjust if route logging changes to
											// interpolate userId
		String result = (String) controller.createProduct((String) "Item", (double) 3.21d, (int) 11,
				(int) distinctiveUserId, (String) "List");
		assertEquals((String) "Produto Criado", (String) result);
		ArgumentCaptor<LogModel> logCaptor = ArgumentCaptor.forClass(LogModel.class);
		verify(Log, times(1)).save(logCaptor.capture());
		LogModel logged = logCaptor.getValue();
		assertTrue(objectHasStringFieldWithValue(logged, (String) "product/create/{userid}"));
		assertFalse(objectHasStringFieldWithValue(logged, (String) ("product/create/" + distinctiveUserId)));
	}

	private boolean objectHasStringFieldWithValue(Object obj, String expected) {
		if (obj == null)
			return false;
		Class<?> c = obj.getClass();
		while (c != null) {
			java.lang.reflect.Field[] fields = c.getDeclaredFields();
			for (java.lang.reflect.Field f : fields) {
				if (f.getType() == String.class) {
					try {
						f.setAccessible(true);
						Object val = f.get(obj);
						if (expected == null) {
							if (val == null)
								return true;
						}
						else if (expected.equals(val)) {
							return true;
						}
					}
					catch (IllegalAccessException ignored) {
					}
				}
			}
			c = c.getSuperclass();
		}
		return false;
	}

	private boolean objectHasDoubleFieldWithValue(Object obj, double expected) {
		if (obj == null)
			return false;
		Class<?> c = obj.getClass();
		while (c != null) {
			for (java.lang.reflect.Field f : c.getDeclaredFields()) {
				try {
					f.setAccessible(true);
					if (f.getType() == double.class) {
						double v = f.getDouble(obj);
						if (Double.isNaN(expected) && Double.isNaN(v))
							return true;
						if (Double.compare(v, expected) == 0)
							return true;
					}
					else if (f.getType() == Double.class) {
						Object val = f.get(obj);
						if (val instanceof Double) {
							double v = (Double) val;
							if (Double.isNaN(expected) && Double.isNaN(v))
								return true;
							if (Double.compare(v, expected) == 0)
								return true;
						}
					}
				}
				catch (IllegalAccessException ignored) {
				}
			}
			c = c.getSuperclass();
		}
		return false;
	}

	private boolean objectHasNaNDoubleField(Object obj) {
		if (obj == null)
			return false;
		Class<?> c = obj.getClass();
		while (c != null) {
			for (java.lang.reflect.Field f : c.getDeclaredFields()) {
				try {
					f.setAccessible(true);
					if (f.getType() == double.class) {
						double v = f.getDouble(obj);
						if (Double.isNaN(v))
							return true;
					}
					else if (f.getType() == Double.class) {
						Object val = f.get(obj);
						if (val instanceof Double && Double.isNaN((Double) val))
							return true;
					}
				}
				catch (IllegalAccessException ignored) {
				}
			}
			c = c.getSuperclass();
		}
		return false;
	}

	private boolean objectHasIntFieldWithValue(Object obj, int expected) {
		if (obj == null)
			return false;
		Class<?> c = obj.getClass();
		while (c != null) {
			for (java.lang.reflect.Field f : c.getDeclaredFields()) {
				try {
					f.setAccessible(true);
					if (f.getType() == int.class) {
						int v = f.getInt(obj);
						if (v == expected)
							return true;
					}
					else if (f.getType() == Integer.class) {
						Object val = f.get(obj);
						if (val instanceof Integer && ((Integer) val) == expected)
							return true;
					}
				}
				catch (IllegalAccessException ignored) {
				}
			}
			c = c.getSuperclass();
		}
		return false;
	}

}